### ISSUE TITLE
Search bar bug

### ISSUE THREAD

**Issue by Tsarcasm** [MemeEcon/MemeEcon.github.io#3]
I have tested the system implemented and it seems as if there is an error with this function:

```
$('.search-bar').val('');

        reload = function(keyinput) {

            if(event.keyCode == 13) {

                featuredQuote = keyinput.value;

                myChart.destroy();

                createLoader();

                fetchData(featuredQuote);

            }

        }
```
Doing some console testing, myChart.destroy() produces an error for unknown reasons, and there may be another error with event triggering of the searchbar.

Just FYI
p.s. great job with the site so far!

**Comment by Tsarcasm** [comment]
In particular the error

> ReferenceError: event is not defined

was returned, there may be an error with the jQuery somewhere.

**Comment by MemeEcon** [comment]
This is an error almost exclusive to Firefox because it doesn't use an event listener like any other browser. I've switched over to a jQuery key listener but Firefox still isn't working. I'll keep working on it, thank you.

**Comment by MemeEcon** [comment]
fixed it. I changed keyCode to charCode in the process of debugging which firefox handles different from keyCode, so I switched it back and it works fine now 👍
