### ISSUE TITLE
How to Contribute

### ISSUE THREAD

**Issue by aeolingamenfel** [MemeEcon/MemeEcon.github.io#4]
Is there a place where there is some sort of roadmap or feature set or something so that others can contribute? I would love to contribute to the project but don't know how to and don't want to step on toes.

**Comment by muhammadtalhas** [comment]
Hey, thanks for your interest. We've unfortunately moved into a private repository and this repository is out of date and abandoned. We're currently overwhelmed with people wanting to help out and for right now have stopped accepting applications. I've gone ahead and alerted the team that you'd like to help and attached you're github. If we need help in the future, well reach out to you

**Comment by aeolingamenfel** [comment]
Thanks, sounds good.
